apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cat2bug-data
  namespace: __NAMESPACE__
  labels:
    app: cat2bug
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
