apiVersion: v1
kind: Service
metadata:
  name: cat2bug
  namespace: __NAMESPACE__
  labels:
    app: cat2bug
spec:
  type: ClusterIP
  selector:
    app: cat2bug
  ports:
    - name: web
      port: 8000
      targetPort: web
      protocol: TCP
